### PR TITLE
Bug fixes (allows to build correctly on Jenkins)

### PR DESCRIPTION
**Pull request by furbrain**

### CODE REVIEW

**Comment by joerick** [comment]
Wow, lightning fast! There's another problem - `wget` not installed. Could we switch to `curl` for the download?

**Comment by furbrain** [comment]
ok, done.

Phil

**Comment by joerick** [comment]
Let's see what Jenkins makes of that!

**Comment by joerick** [comment]
Hmm. Still failing. Let me try here, maybe that's a GNU tar feature that's not available.

**Comment by joerick** [comment]
That's building again.

**Pull request merged**
